# Generated by Django 5.1 on 2024-10-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fname_savedform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedform',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
